# Generated by Django 4.2.16 on 2024-10-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Фотография')),
                ('name', models.CharField(max_length=45, verbose_name='Имя студента')),
                ('surname', models.CharField(max_length=45, verbose_name='Фамилия студента')),
                ('point', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Балы')),
                ('number', models.CharField(max_length=25, verbose_name='Номер студента')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Truancie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='Причина прогула')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.student', verbose_name='Студент')),
            ],
        ),
    ]
