# Generated by Django 5.1.3 on 2024-11-25 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('version', models.PositiveIntegerField(default=1)),
                ('rules_list', models.JSONField(verbose_name='Свод правил')),
            ],
            options={
                'verbose_name_plural': 'Правило сайта',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Фотография')),
                ('name', models.CharField(max_length=45, verbose_name='Имя студента')),
                ('surname', models.CharField(max_length=45, verbose_name='Фамилия студента')),
                ('point', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Балы')),
                ('number', models.CharField(max_length=25, verbose_name='Номер студента')),
                ('place_rating', models.PositiveIntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Truancie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='Причина прогула')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name_plural': 'Прогулы студентов',
            },
        ),
    ]
