# Generated by Django 4.2.16 on 2024-10-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truancie',
            options={'verbose_name_plural': 'Прогулы студентов'},
        ),
    ]
