# Generated by Django 5.1.3 on 2024-11-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rules',
            options={'verbose_name_plural': 'Правила сайта'},
        ),
    ]
