# Generated by Django 4.2.16 on 2024-10-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_truancie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='place_rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
